#version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - temp:/temp

    environment:
      - WORK_DIR:/temp
    env_file:
      - .env
    restart: unless-stopped

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - temp:/temp
    env_file:
      - .env
    environment:
      - WORK_DIR:/temps
    restart: unless-stopped

volumes:
  temp:
