name: ai_agents
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - ffmpeg=7.1
  - pip=24.0
  - cudatoolkit=11.8.0
  - pytorch=2.2.2
  - torchaudio=2.2.2
  - torchvision=0.17.2
  - numpy=1.26
  - typing-extensions=4.12
  - tqdm=4.67
  - requests=2.32
  - python-dotenv=1.0
  - pip:
      - fastapi==0.115.6
      - uvicorn==0.34.0
      - pydantic==2.10.5
      - pydantic-settings==2.7.1
      - python-multipart==0.0.20
      - openai==1.59.8
      - langchain-openai==0.3.6
      - langchain-core==0.3.35
      - moviepy==2.1.2
      - openai-whisper==20240930
      - tiktoken==0.8.0
      - python-dateutil==2.9.0
      - pydub==0.25.1
      - python-json-logger==3.2.1
      - psutil==6.1.1
      - loguru==0.7.2
      - jinja2==3.1.5
      - pytelegrambotapi==4.26.0
      - requests-toolbelt==1.0.0
      - aiohttp==3.11.1
