name: ai_agents
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.11
  - ffmpeg=7.1.0
  - requests=2.32.3
  - pip=24.2
  - brotli-python=1.0.9
  - certifi=2025.1.31
  - openssl=3.4.1
  - sqlite=3.45.3
  - tzdata=2024b
  - x264=1!164.3095
  - x265=3.5
  - zlib=1.3.1
  - pip:
      - telebot==0.0.5
      - pytubefix
      - pytube
      - pydub
