name: ai_bot
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - ffmpeg=6.0
  - pip=23
  - openssl=3
  - pip:
      - pytelegrambotapi
      - telebot
      - pytube==15.0.0
      - telebot==0.0.5
      - pytubefix==8.12.2
      - pydub==0.25.1
      - requests==2.31.0
      - python-dotenv
