name: ai_bot
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - ffmpeg=6.0
  - pip=23
  - openssl=3

  - pip:
      - pytelegrambotapi==4.26.0
      - pytube==15.0.0
      - telebot
      - pytubefix==8.12.2
      - pydub==0.25.1
      - requests==2.31.0
